#!/bin/bash

echo "Rebashing..."

if [ ! -d "$HOME/home"  ]; then
    echo "no $HOME/home"
    echo "git clone https://github.com/markturansky/dotfiles.git $HOME"
    exit
fi

source ~/home/shell/functions.sh
platform && echo "Platform: $platform"

alias ll='ls -l'
alias la='ls -la'




#
# Git
#

# replace existing .git configs with links to the repo version
ln -sf ~/home/shell/.gitconfig_$platform ~/.gitconfig
ln -sf ~/home/shell/.gitignore_global ~/.gitignore_global
alias gs='git status'
alias gc="git checkout"

source ~/home/shell/git-completion.sh

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true

# Color setup
prompt_title="\033]0;\W\007\n\[\e[1;37m\]"
prompt_glyph="★"

color_reset="\[\e[0;39m\]"
color_user="\[\e[1;33m\]"
color_host="\[\e[1;36m\]"
color_pwd="\[\e[1;33m\]"
color_git="\[\e[0;36m\]"
color_glyph="\[\e[35;40m\]"

# Thy holy prompt.
PROMPT_COMMAND='history -a;PS1="${prompt_title}${color_glyph}${prompt_glyph}${color_reset} ${color_user}\u${color_reset}:${color_pwd}\w${color_reset}${color_git} ${color_reset} \[\e[1;37m\]${color_reset}\n$ "'

export TERM="xterm-color" PS1='\[\e[0;33m\]\u\[\e[0m\]@\[\e[0;32m\]\h\[\e[0m\]:\[\e[0;34m\]\w\[\e[0m\]\$ '



